# Generated by Django 4.2.30 on 2026-09-11 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='分支全名')),
                ('type', models.CharField(choices=[('feature', 'feature'), ('bugfix', 'bugfix')], max_length=20, verbose_name='分支类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '开发分支',
                'verbose_name_plural': '开发分支',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='项目名称')),
                ('local_path', models.CharField(max_length=500, verbose_name='本地仓库路径')),
                ('remote_url', models.CharField(default='origin', help_text='例如 origin；也可以填写完整 Git URL。', max_length=500, verbose_name='远程名称或 URL')),
                ('stable_branch', models.CharField(default='stable', max_length=120, verbose_name='stable 分支')),
                ('uat_branch', models.CharField(default='uat', max_length=120, verbose_name='UAT 分支')),
                ('build_script', models.CharField(default='build.sh', help_text='相对于仓库根目录的脚本路径。', max_length=500, verbose_name='SaaS 打包脚本')),
                ('release_command_template', models.TextField(blank=True, help_text='可选。支持 {release}、{package_path}、{repository} 占位符；仅用于复制，不会自动执行。', verbose_name='生产发布命令模板')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '仓库',
                'verbose_name_plural': '仓库',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UATRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待测试'), ('testing', '测试中'), ('passed', '测试通过'), ('failed', '测试失败')], default='pending', max_length=20, verbose_name='UAT 状态')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('merged_commit', models.CharField(blank=True, max_length=64, verbose_name='已合入 UAT 的分支提交')),
                ('merged_at', models.DateTimeField(blank=True, null=True, verbose_name='最近合入 UAT 时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uat_record', to='workbench.branch', verbose_name='开发分支')),
            ],
            options={
                'verbose_name': 'UAT 记录',
                'verbose_name_plural': 'UAT 记录',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Release 分支')),
                ('status', models.CharField(choices=[('merging', '正在合并'), ('merge_failed', '合并冲突'), ('merged', '已合并'), ('ready', '检查通过'), ('building', '正在构建'), ('build_failed', '构建失败'), ('build_success', '构建成功'), ('production_verified', '生产验证通过'), ('stable_merged', '已合入 stable')], default='merging', max_length=40, verbose_name='状态')),
                ('base_commit', models.CharField(blank=True, max_length=64, verbose_name='基于的 stable 提交')),
                ('check_result', models.TextField(blank=True, verbose_name='检查结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('production_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='生产验证时间')),
                ('stable_merged_at', models.DateTimeField(blank=True, null=True, verbose_name='合入 stable 时间')),
                ('branches', models.ManyToManyField(related_name='releases', to='workbench.branch', verbose_name='包含的开发分支')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='workbench.repository', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Release',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GitOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=120, verbose_name='操作人')),
                ('action', models.CharField(max_length=120, verbose_name='动作')),
                ('command', models.TextField(verbose_name='命令')),
                ('result', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=20, verbose_name='结果')),
                ('stdout', models.TextField(blank=True, verbose_name='stdout')),
                ('stderr', models.TextField(blank=True, verbose_name='stderr')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_logs', to='workbench.repository', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'Git 操作日志',
                'verbose_name_plural': 'Git 操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('building', '构建中'), ('success', '成功'), ('failed', '失败')], default='building', max_length=20, verbose_name='状态')),
                ('log', models.TextField(blank=True, verbose_name='构建日志')),
                ('package_path', models.CharField(blank=True, max_length=1000, verbose_name='SaaS 包路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='build_record', to='workbench.release', verbose_name='Release')),
            ],
            options={
                'verbose_name': '构建记录',
                'verbose_name_plural': '构建记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='workbench.repository', verbose_name='仓库'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(fields=('repository', 'name'), name='unique_repository_release'),
        ),
        migrations.AddIndex(
            model_name='gitoperationlog',
            index=models.Index(fields=['repository', '-created_at'], name='workbench_g_reposit_b15cca_idx'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('repository', 'name'), name='unique_repository_branch'),
        ),
    ]
