# Generated by Django 4.2.30 on 2026-09-11 06:15

import django.db.models.deletion
from django.db import migrations, models


def migrate_release_status_forward(apps, schema_editor):
    Release = apps.get_model("workbench", "Release")
    Release.objects.filter(status="stable_merged").update(status="baseline_merged")


def migrate_release_status_backward(apps, schema_editor):
    Release = apps.get_model("workbench", "Release")
    Release.objects.filter(status="baseline_merged").update(status="stable_merged")


class Migration(migrations.Migration):

    dependencies = [
        ("workbench", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="repository",
            old_name="stable_branch",
            new_name="baseline_branch",
        ),
        migrations.AlterField(
            model_name="repository",
            name="baseline_branch",
            field=models.CharField(
                default="stable",
                help_text="Release 从这里创建，生产验证后也合入这里；默认 stable。",
                max_length=120,
                verbose_name="发布基线分支",
            ),
        ),
        migrations.RenameField(
            model_name="repository",
            old_name="uat_branch",
            new_name="verification_branch",
        ),
        migrations.AlterField(
            model_name="repository",
            name="verification_branch",
            field=models.CharField(
                default="uat",
                help_text="用于合入待验证分支；可配置为 uat、sit、qa 等项目实际名称。",
                max_length=120,
                verbose_name="验证分支",
            ),
        ),
        migrations.RenameModel(
            old_name="UATRecord",
            new_name="VerificationRecord",
        ),
        migrations.AlterModelOptions(
            name="verificationrecord",
            options={
                "verbose_name": "验证记录",
                "verbose_name_plural": "验证记录",
            },
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="branch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="verification_record",
                to="workbench.branch",
                verbose_name="开发分支",
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="merged_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="最近合入验证分支时间",
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="merged_commit",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="已合入验证分支的提交",
            ),
        ),
        migrations.AlterField(
            model_name="verificationrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待验证"),
                    ("testing", "验证中"),
                    ("passed", "验证通过"),
                    ("failed", "验证失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="验证状态",
            ),
        ),
        migrations.RenameField(
            model_name="release",
            old_name="stable_merged_at",
            new_name="baseline_merged_at",
        ),
        migrations.AlterField(
            model_name="release",
            name="baseline_merged_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="合入发布基线时间",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="base_commit",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="基于的发布基线提交",
            ),
        ),
        migrations.AlterField(
            model_name="release",
            name="status",
            field=models.CharField(
                choices=[
                    ("merging", "正在合并"),
                    ("merge_failed", "合并冲突"),
                    ("merged", "已合并"),
                    ("ready", "检查通过"),
                    ("building", "正在构建"),
                    ("build_failed", "构建失败"),
                    ("build_success", "构建成功"),
                    ("production_verified", "生产验证通过"),
                    ("baseline_merged", "已合入发布基线"),
                ],
                default="merging",
                max_length=40,
                verbose_name="状态",
            ),
        ),
        migrations.RunPython(
            migrate_release_status_forward,
            migrate_release_status_backward,
        ),
    ]
