# Generated by Django 4.2.30 on 2026-09-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0002_standardize_branch_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='build_script',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='release_command_template',
        ),
    ]
