# Generated by Django 4.2.30 on 2026-09-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0003_remove_custom_build_and_release_command_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='saas_build_enabled',
            field=models.BooleanField(default=True, help_text='启用后在 Release 检查通过时可执行仓库根目录的 build.sh。', verbose_name='启用 SaaS 打包'),
        ),
    ]
