# Generated by Django 4.2.30 on 2026-09-11 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0004_add_optional_saas_build'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('create_branch', '创建开发分支'), ('merge_verification', '合入验证分支'), ('create_release', '创建 Release'), ('continue_release_merge', '继续合并 Release'), ('merge_baseline', '合入发布基线'), ('checkout_for_build', '切换构建分支')], max_length=40, verbose_name='操作类型')),
                ('target', models.CharField(max_length=300, verbose_name='目标')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('succeeded', '已完成'), ('failed', '执行前失败'), ('unknown', '结果待确认')], default='pending', max_length=20, verbose_name='状态')),
                ('idempotency_key', models.CharField(max_length=300, unique=True, verbose_name='幂等键')),
                ('log', models.TextField(blank=True, verbose_name='执行日志')),
                ('final_sha', models.CharField(blank=True, max_length=64, verbose_name='最终 SHA')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_operations', to='workbench.repository', verbose_name='仓库')),
            ],
            options={
                'verbose_name': 'Git 自动操作',
                'verbose_name_plural': 'Git 自动操作',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['repository', '-created_at'], name='workbench_g_reposit_310b09_idx'), models.Index(fields=['repository', 'status'], name='workbench_g_reposit_ad4a27_idx')],
            },
        ),
    ]
