# Generated by Django 4.2.30 on 2026-09-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0005_add_git_operation_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='放弃时间'),
        ),
        migrations.AlterField(
            model_name='release',
            name='status',
            field=models.CharField(choices=[('merging', '正在合并'), ('merge_failed', '合并冲突'), ('merged', '已合并'), ('ready', '检查通过'), ('building', '正在构建'), ('build_failed', '构建失败'), ('build_success', '构建成功'), ('production_verified', '生产验证通过'), ('baseline_merged', '已合入发布基线'), ('cancelled', '已放弃')], default='merging', max_length=40, verbose_name='状态'),
        ),
    ]
