# Generated by Django 4.2.30 on 2026-09-11 07:19

from django.db import migrations, models


def move_build_statuses_to_ready(apps, schema_editor):
    Release = apps.get_model("workbench", "Release")
    Release.objects.filter(
        status__in=["building", "build_failed", "build_success"]
    ).update(status="ready")


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0006_add_release_cancellation'),
    ]

    operations = [
        migrations.RunPython(
            move_build_statuses_to_ready,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='release',
            name='status',
            field=models.CharField(choices=[('merging', '正在合并'), ('merge_failed', '合并冲突'), ('merged', '已合并'), ('ready', '检查通过'), ('production_verified', '生产验证通过'), ('baseline_merged', '已合入发布基线'), ('cancelled', '已放弃')], default='merging', max_length=40, verbose_name='状态'),
        ),
    ]
