# Generated by Django 6.0.1 on 2026-09-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0007_decouple_saas_build_from_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitoperationlog',
            name='stderr',
            field=models.TextField(blank=True, null=True, verbose_name='stderr'),
        ),
        migrations.AlterField(
            model_name='gitoperationlog',
            name='stdout',
            field=models.TextField(blank=True, null=True, verbose_name='stdout'),
        ),
    ]
