# Generated by Django 4.2.30 on 2026-09-14 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0008_alter_gitoperationlog_stderr_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GitOperation',
        ),
    ]
