# Generated by Django 4.2.30 on 2026-09-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0009_delete_gitoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='removed',
            field=models.BooleanField(default=False, verbose_name='已从界面移除'),
        ),
    ]
